name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main # Replace 'main' with your default branch if needed

permissions:
  id-token: write # Grant the necessary permissions for the deploy-pages action
  contents: write # Ensure content write access for deployment
  pages: write # Allow deployment to GitHub Page

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.2.1

        # Set up Python
      - name: Set up Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: "3.10"

        # Install dependencies and sphinx
      - name: Install Dependencies
        run: |
          pip install sphinx sphinx-rtd-theme

        # Install requirements for documentation building
      - name: Install Documentation Requirements
        run: |
          pip install -r client_requirements_nvidia.txt

        # Build the Sphinx documentation
      - name: Build Sphinx Documentation
        run: |
          cd ./docs
          sphinx-build -b html ./ ./_build/html

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0

      # Create a tarball of the built documentation
      - name: Zip artifact
        run: |
          tar -czvf html.tar.gz ./docs/_build/html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@0252fc4ba7626f0298f0cf00902a25c6afc77fa8 # v3.0
        with:
          # Upload entire repository
          path: "./docs/_build/html"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e #v4.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
